import { headers } from "next/headers";
import { notFound, redirect } from "next/navigation";
import type { LabDetail } from "@curated-labs/shared";
import { getMe } from "@/lib/session";
import { serverApi } from "@/lib/server-api";
import { Alert } from "@/components/ui";
import { tokens } from "@/lib/tokens";
import { LabShell } from "@/features/labs/LabShell";

export default async function PlaygroundScenarioPage({
  params,
}: {
  params: Promise<{ scenarioId: string }>;
}) {
  const { scenarioId } = await params;
  const cookie = (await headers()).get("cookie") ?? undefined;

  const me = await getMe(cookie);
  if (!me) redirect(`/login?returnTo=/app/playground/${scenarioId}`);

  // This payload carries no threats, mitigation mapping or release guidance —
  // the same LabDetail shape and the same reason as a curated lab (§28).
  const scenario = await serverApi<LabDetail>(`/playground/scenarios/${scenarioId}`, cookie);
  if (!scenario) notFound();

  return (
    <>
      <div style={{ padding: `${tokens.space(4)} ${tokens.space(7)} 0` }}>
        <Alert tone="info">
          Practice scenario — this was generated by AI and its answer key has not been reviewed by a human curator.
        </Alert>
      </div>
      <LabShell
        lab={scenario}
        attemptId={scenario.attempt?.id}
        startPath={`/playground/scenarios/${scenario.id}/attempts`}
        attemptBase="/playground/attempts"
        backHref="/app/playground"
      />
    </>
  );
}
